name:         Anti-pattern
markdown:     redcarpet
highlighter:  rouge
permalink:    /:title
archive_path: /archive
exclude:      ["vendor"]
baseurl:      http://anti-pattern.com

redcarpet:
  extensions: ["footnotes", "smart", "hard_wrap"]

gems: ["./lib/redcarpet_ext"]
